var ICS-Directory = {
    top_level: [“arts”, ”business”, ”entertainment”, ”news”, ”religion”],

	“arts”: [“visual arts”, ”literature”, ”comics”],
	“business”: [“careers”, ”investing”],
	“entertainment”: [“games”, ”comics”, ”toys”, ”movies”, ”food”, ”sports”],
	“news”: [“cable news”, ”network news”, ”sports”, ”weather”, ”science”, ”technology”],
	“religion”: [“buddhism”, ”hinduism”, ”christianity”, ”islam”, ”judaism”, ”atheism”, ”shinto”],

    "geo_location": ["north america", "africa", "asia", "europe"],
    "north america": ["usa", "canada", "mexico"],
    "usa": ["washington", "oregon", "idaho", "california"],
    "washington": ["seattle", "spokane", "tacoma"],
    "seattle": ["seattle mariners", "seattle seahawks", "seattle sounders"],

	“visual arts”: [“paint”, ”charcoal”, ”pencil”, ”chalk”, ”ink”, ”sculpture”, ”wood”, ”illustration”, ”graphic design”],
	“literature”: [“books”, ”comics”, ”poetry”, ”drama”],
	“comics”: [“golden age”, “silver age”, ”bronze age”, ”modern age”, “marvel”, ”dc”, ”idw”, ”image”, ”dark horse”],

    “games”: [“tabletop games”, ” video games”],
    “toys”: [“antique: pre 1960”, ”vintage: 1961-1999”, ”modern: 2000-today”],
	“movies”: [“classic cinema”, ”modern film”],
	“food”: [“entertaining”, ”resturants”, ”recipes”],
	“sports”: [“football (american football)”, ”soccer (football)”, ”baseball”, ”basketball”, ”wrestling”, ”boxing”, ”MMA”, ”rugby”, ”golf”, ”hockey”, ”archery”, ”firearms”, ”jousting”, ”water sports”, ”winter sports”],
	
	“weather”: [“northeastern USA”, ”southeastern USA”, ”midwest USA”, ”northwestern USA”, ”southwestern USA”, ”europe”, ”china”, ”south america”, ”australia”, ”japan”, ”africa”, ”india”, ”pacific islands”, ”mexico”, ”canada”],
	“science”: [“engineering”, ”theoretical”, ”biology”, ”chemistry”, ”mathematics”, ”quantum mechanics”, ”physics”, ”nature”, ”archiology”, ”astronomy”, ”anthropology”],
	“technology”: [“gadgets”, ”tech news”],

	“paint”: [“acrylics”, ”oils”, ”watercolor”],
	
    “books”: [“fiction”, ”non-fiction”],
    “tabletop games”: [“role playing games”, ”board games”, ”card games”],
    “video games”: [“computer”, ”console”],

    “console”: [“playstation”, ”nintendo”,”x-box”],

    “football (american football)”: [“NFL”, ”NCAA”],
    “soccer (football)”: [“Major League Soccer“, ”FIFA World Cup“],
    ”baseball”: [“New York Yankees”, ”Philadelphia Phillies”, ”Boston Red Sox”, ”Los Angeles Angels of Anaheim”, ”Chicago White Sox”, ”Chicago Cubs”, ”New York Mets”, ”San Francisco Giants”, ”Minnesota Twins”, ”Detroit Tigers”, ”St. Louis Cardinals”, ”Los Angeles Dodgers”, ”Texas Rangers”, ”Colorado Rockies”, ”Atlanta Braves”, ”Seattle Mariners”, ”Milwaukee Brewers”, ”Baltimore Orioles”, ”Cincinnati Reds”, ”Houston Astros”, ”Oakland Athletics”, ”Washington Nationals”, ”Toronto Blue Jays”, ”Miami Marlins”, ”Arizona Diamondbacks”, ”Cleveland Indians”, ”San Diego Padres”, ”Pittsburgh Pirates”, ”Tampa Bay Rays”, ”Kansas City Royals”],
    ”basketball”: [],
    ”wrestling”: [],
    ”boxing”: [],
    ”MMA”: [],
    “rugby”: [],
    ”golf”: [],
    ”hockey”: [],
    ”archery”: [],
    ”firearms”: [],
    ”jousting”: [],
    ”water sports”: [“water skiing”, ”wakeboarding”, ”surfing”, ”inland wake surfing”, ”swimming”, ”water polo”],
    ”winter sports”: [“skiing”, ”snowboarding”, ”snowshoeing”, ”sledding”],

    “NFL”: [“AFC north”, ”NFC north“, ”AFC south”, ”NFC south”, ”AFC east”, ”NFC east”, ”AFC west”, ”NFC west”],
    “AFC north”: [“Baltimore Ravens”, ”Cincinnati Bengals”, ”Cleveland Browns”, ”Pittsburgh Steelers”],
    ”NFC north“: [“Chicago Bears”, ”Detroit Lions”, ”Green Bay Packers”, ”Minnesota Vikings”],
    ”AFC south”: [“Houstan Texans”, ”Indianapolis Colts”, ”Jacksonville Jaguars”, ”Tennessee Titans”],
    ”NFC south”: [“Atlanta Falcons”, ”Carolina Panthers”, ”New Orleans Saints”, ”Tampa Bay Buccaneers”],
    ”AFC east”: [“Buffalo Bills”, ”Miami Dolphins”, ”New England Patriots”, ”New York Jets”],
    ”NFC east”: [“Dallas Cowboys”, ”New York Giants”, ”Philadelphia Eagles”, ”Washington Redskins”],
    ”AFC west”: [“Denver Broncos”, ”Kansas City Chiefs”, ”Oakland Raiders”, ”San Diego Chargers”],
    ”NFC west”: [“Arizona Cardinals”, ”San Fransisco 49ers”, ”Seattle Seahawks”, ”St. Louis Rams”],

    “NCAA”: [“AAC”, ”ACC”, ”Big 12”, ”Big Ten”, ”Conference USA”, ”Independents”, ”MAC”, ”Mountain West”, ”PAC-12”, ”SEC”, ”Sun Belt”, ”Big South”, ”Big Sky”, ”Colonial Athletic Assoc.”, ”Ivy League”, ”Mid-Eastern Athletics”, ”Missoury Valley”, ”Northeast”, ”Ohio Valley”, ”Patriot League”, ”Pioneer League”, ”Southern”, ”Southland”, ”Southwestern Athletic”],
    “AAC”: [“Cincinnati Bearcats”, ”Connecticut Huskies”, ”East Carolina Pirates”, ”Houston Cougars”, ”Memphis Tigers”, ”SMU Mustangs”, ”South Florida Bulls”, ”Temple Owls”, ”Tulane Green Wave”, ”Tulsa Golden Hurricane”, ” UCF Knights”],
    ”ACC”: [“],
    ”Big 12”: [],
    ”Big Ten”: [],
    ”Conference USA”: [],
    ”Independents”: [],
    ”MAC”: [],
    ”Mountain West”: [],
    ”PAC-12”: [],
    ”SEC”: [],
    ”Sun Belt”: [],
    ”Big South”: [],
    ”Big Sky”: [],
    ”Colonial Athletic Assoc.”: [],
    ”Ivy League”: [],
    ”Mid-Eastern Athletics”: [],
    ”Missoury Valley”: [],
    ”Northeast”: [],
    ”Ohio Valley”: [],
    ”Patriot League”: [],
    ”Pioneer League”: [],
    ”Southern”: [],
    ”Southland”: [],
    ”Southwestern Athletic”: [],
    
}
